version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: mhart/alpine-node:8.5.0
    working_directory: ~/app
    steps:
      - checkout
      - run:  | 
            npm install --force \
            npm update --force \
            npm run test
      - run:
          name: Install jFrog CLI
          command: wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.7.1/jfrog-cli-linux-amd64/jfrog
            - chmod +x jfrog
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog config add $JFROG_SERVER --artifactory-url $ARTIFACTORY_URL --user $JFROG_USER --apikey $JFROG_API_KEY --interactive=false
            ./jfrog rt u "default-npm-remote.js" default-npm-remote --build-name=nodeapp-alexm --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce nodeapp-alexm $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp nodeapp-alexm $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory


workflows:
  build-node:
    jobs:
      - build