version: 2.1
orbs:
  node: circleci/node@5.0.2
  artifactory-orb: jfrog/artifactory-orb@1.0.1

jobs:
  local_build:
    docker:
 #     - image: ubuntu:latest
      - image: circleci/node:10
    working_directory: ~/node/app
    steps:
    #  - run: apt-get update -y && apt-get -y install nodejs npm && apt-get install curl -y && apt autoclean && apt autoremove
      - checkout
      - run:  | 
            npm install mocha -g \
            sudo npm install --force \
            sudo npm update --force
      - run: 
          name: Run nodejs test
          command: npm run test
      - store_test_results:
          path: ~/node/
    
  uploading_artifacts:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |
            npm install --force \
            npm update --force
      - run: cd .. && tar -zcvf nodeapp.tar.gz app
      - store_artifacts:
          path: ~/node/nodeapp.tar.gz
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Configure JFROG CLI
          command: |
            ./jfrog config add $JFROG_SERVER --artifactory-url $ARTIFACTORY_URL --user $JFROG_USER --password $JFROG_API_KEY --interactive=false --enc-password=false --basic-auth-only=true
      - run: 
          name: Upload artifacts to JFROG
          command: ./jfrog rt u app/ default-npm-local



    # docker:
    #   - image: node:latest
    # working_directory: ~node/app
    # steps:
    #   - checkout
    #   - artifactory/install
    #   - artifactory/configure
    #   - artifactory/docker-publish:
    #       docker-registry: $JFROG_SERVER
    #       docker-steps: 
    #         - run: docker build -t $DOCKERTAG docker-publish-node
    #       docker-tag: >-
    #          $JFROG_SERVER/nodeapp:1.0-${CIRCLE_BUILD_NUM}
    #       name: Docker Publish Build
    #       repository: default-docker-local



    

            


  #The comments below steps are JFROG. Which the confirmation is currently not working and is still WIP. 
      # - run:
      #     name: Install jFrog CLI
      #     command: curl -fL https://getcli.jfrog.io | sh
      # - run:
      #     name: Configure JFROG CLI
      #     command: |
      #       ./jfrog config add $JFROG_SERVER --artifactory-url $ARTIFACTORY_URL --user $JFROG_USER --password $JFROG_API_KEY --interactive=false --enc-password=false --basic-auth-only=true
      # - run:
      #     name: running the build to jfrog
      #     command: |
      #       ./jfrog rt u app default-npm-remote --build-name=nodeapp-alexm --build-number=$CIRCLE_BUILD_NUM
      #       ./jfrog rt bce nodeapp-alexm $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
      #       ./jfrog rt bp nodeapp-alexm $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory


workflows:
  build-node:
    jobs:
      - local_build
      - uploading_artifacts:
          type: approval
          requires:
            - local_build


