version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: ~/node/app
    steps:
      - run: apt-get update -y && apt-get -y install nodejs npm && apt-get install curl -y && apt autoclean && apt autoremove
      - checkout
      - run:  | 
            npm install --force \
            npm update --force \
            npm run
      - run: cd .. && tar -zcvf nodeapp.tar.gz app
      - run:  | 
            PATH=$PATH:`pwd` \
            pwd
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Configure JFROG CLI
          command: |
            ./jfrog config add $JFROG_SERVER --artifactory-url $ARTIFACTORY_URL --user $JFROG_USER --password $JFROG_API_KEY --interactive=false --enc-password=false --basic-auth-only=true
      - run:
          name: running the build to jfrog
          command: |
            ./jfrog rt u $PATH/app default-npm-remote --build-name=nodeapp-alexm --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce nodeapp-alexm $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp nodeapp-alexm $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory


workflows:
  build-node:
    jobs:
      - build

