version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: ~/app
    steps:
      - run: apt-get update -y && apt-get -y install nodejs npm && apt-get install wget -y && apt autoclean && apt autoremove
      - checkout
      - run:  | 
            npm install --force \
            npm update --force \
            npm run test
      - run:
          name: Install jFrog CLI
          command: |
            wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | apt-key add - \
            echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | tee -a /etc/apt/sources.list; \
            apt install -y jfrog-cli-v2-jf; 
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog config add $JFROG_SERVER --artifactory-url $ARTIFACTORY_URL --user $JFROG_USER --apikey $JFROG_API_KEY --interactive=false
            ./jfrog rt u "default-npm-remote.js" default-npm-remote --build-name=nodeapp-alexm --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce nodeapp-alexm $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp nodeapp-alexm $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory


workflows:
  build-node:
    jobs:
      - build

