version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: mhart/alpine-node:8.5.0
    working_directory: ~/app
    steps:
      - checkout
      - run:  | 
            npm install --force \
            npm update --force \
            npm run test

workflows:
  build-node:
    jobs:
      - build